# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f03493afa659090dd0a81ae6f8c38fea7a6f74db8f7bad6bbe46a173f6f64426a3cfd5dec3d53ffe38f650f1570a1a8c899abfe8fc4956ffd31849eedfdd478b

test:
  secret_key_base: 6b1cd859b98d4c00866e7bccca993cd1ed5b45f4962db4bdc5093039997e14a49350ec5bb581e664bff15fc29826e051f128bd8534d34420efb1c7cb1633b88e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
