# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13a748902ca557a4783e83aa6b269c3f00c00ddad99637f51afe71b4f67ae88462bf170ca3f702d6edc829ce8164915731e689234b1105dda29752486f5f803f

test:
  secret_key_base: 9dc1e7cbc872f0ee6e11dfbd6b5c7e821b07bdf97c33689edaf3515ad4d3c5ac7ea4173e5da6ef51e13623e4f552bcd1c2b195cd1f87f8da272403e4cfe6d2db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
